#baseURL = "https://optimistic-mestorf-865fd8.netlify.com/é‡‘é’±çˆ†è®°å½•/2020é‡‘é’±çˆ†è®°å½•/"
baseURL = "https://optimistic-mestorf-865fd8.netlify.com"
title = "è¶£è‚¡å­¦å ‚"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
sectionPagesMenu = "main"
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
# Code highlighting options
# Hugo uses Chroma but names are the same as the old pygments highlighter

# Highlight shortcode and code fences (```) will be treated similarly
pygmentscodefences = true

# Change highlight style here.
# For a full list see: https://xyproto.github.io/splash/docs/all.html
pygmentsStyle = "tango" # "emacs" # "autumn" # "manni" # "friendly"

# Other Chroma options can be added here (and in the highlight shortcode in the markdown file)
# See list of supported options: https://gohugo.io/content-management/syntax-highlighting/#options
# for example: pygmentsoptions = "linenos=true"
[params]
	# General information
	author = "Aiden"
	description = "è¶£è‚¡å­¦å ‚"
	copyright = "Released under the Apache 2.0 license"
	

	# Repository
	provider = "GitHub"
	# repo_url = "https://github.com/O-Aiden/stockMarketSite.git"

	version = ""
	# logo = "https://cdn.jsdelivr.net/gh/O-Aiden/cdn@1.2/dog.jpg"
	favicon = "https://cdn.jsdelivr.net/gh/O-Aiden/cdn@1.2/dog.jpg"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
		#primary = "grey"
    	primary = "indigo"
    	accent  = "deep-purple"
		#accent  = "light-green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	github  = "Aiden"
	email   = "hello@email.com"
[[menu.main]]
  	name   = "2020é‡‘é’±çˆ†è®°å½•"
  	url    = "https://optimistic-mestorf-865fd8.netlify.com/é‡‘é’±çˆ†è®°å½•/2020é‡‘é’±çˆ†è®°å½•/"
 	weight = 1
 	pre    = "ğŸ†"
[[menu.main]]
  	name   = "é€šèƒ€æ¨¡å‹"
  	url    = "https://optimistic-mestorf-865fd8.netlify.com/é‡‘é’±çˆ†è®°å½•/åæ ‡test/"
 	weight = 1
 	pre    = "ğŸ†"	 

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
[outputs]
	home = [ "HTML", "JSON"]
	page = [ "HTML", "JSON"]
